feat(vscode): Logic App Workspace Local Settings Updates.
Azure/LogicAppsUX pull request #3087
Opened 2023-08-03 22:57 UTC by samikay101

- **Please check if the PR fulfills these requirements**

* [ X] The commit message follows our guidelines
* [ X] Tests for the changes have been added (for bug fixes/features)
* [ X] Docs have been added / updated (for bug fixes / features)

## Description
This PR includes changes to the Azure Functions configuration and package references. The following modifications have been made:

### Azure Functions Configuration Changes:
- Updated the process name from `'Microsoft.Azure.Workflows.Functions.NetFxWorker.exe'` to `'Microsoft.Azure.Workflows.Functions.CustomCodeNetFxWorker.exe'`.
- Deleted the `'FUNCTIONS_WORKER_RUNTIME'` entry from the local settings.
- Added the `'APP_KIND'` entry with the value `'workflowapp'` to the local settings.

### Package Reference Changes:
- Updated the version of the `'Microsoft.Azure.Workflows.WebJobs.Sdk'` package from `'1.0.1-preview'` to `'1.0.2-preview'`.

## Impact
By updating the process name in the Azure Functions configuration, we ensure compatibility with the `'Microsoft.Azure.Workflows.Functions.CustomCodeNetFxWorker.exe'` process and additional updates to the `'Microsoft.Azure.Workflows.WebJobs.Sdk'` package to version which was updated to`'1.0.2-preview.'`

2023-08-07 16:28 UTC, hartra344 approved these changes

2023-08-07 18:43 UTC, ccastrotrejo requested changes

2023-08-07 18:43 UTC, ccastrotrejo commented on apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/workflowDesigner/DesignerConfig.ts
> -        FUNCTIONS_WORKER_RUNTIME: 'dotnet',
This will be changed to 'node' instead of deleting it

2023-08-07 18:43 UTC, ccastrotrejo commented on apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createLogicApp/ScriptProjectCreateStep.ts
> -          FUNCTIONS_WORKER_RUNTIME: 'dotnet-isolated',
same

2023-08-14 17:36 UTC, ccastrotrejo approved these changes

2023-08-14 18:18 UTC, merged