feat(vscode): Add Integration account source and export custom API actions to export advance options
Azure/LogicAppsUX pull request #4097
Opened 2024-02-01 21:33 UTC by ccastrotrejo

* Adjusted the width of various elements to improve the layout of the export module. This includes removing fixed widths from the input and dropdown elements and adding a new rule to set the width of all child elements of the filters element to 30%. 

* Added two new options to the `AdvancedOptions` component: "Make Integration Account the default source for Transformations and Schema validation" and "Export Custom Connector Actions as API Management Actions". These options are also added to the dropdown in the component.
* Added the keys for the new advanced options to the `AdvancedOptionsTypes` object.

Logic changes:

* Modified the `getAdvanceOptionsSelection` function to filter out certain options when the `generateInfrastructureTemplates` option is selected.
* Updated the `WorkflowsSelection` component for handling the success of the `loadWorkflows` query to accommodate the new advanced options. 

#### Screenshots

https://github.com/Azure/LogicAppsUX/assets/102700317/1595a6d2-140c-4c39-b4f2-e9c0a356a4f6

2024-02-01 21:58 UTC, ccastrotrejo commented on apps/vs-code-react/src/app/export/workflowsSelection/advancedOptions.tsx
> +    INTEGRATION_ACCOUNT_SOURCE: intl.formatMessage({
@ecfan Could you please take a look at the wording for these strings? 
++ @wsilveiranz to be aware of it

2024-02-01 23:44 UTC, ecfan commented on apps/vs-code-react/src/app/export/workflowsSelection/advancedOptions.tsx
> +      defaultMessage: 'Make Integration Account the default source for Transformations and Schema validation',
Consistent capitalization to use sentence case: https://learn.microsoft.com/en-us/style-guide/capitalization

```suggestion
      defaultMessage: 'Default to integration account as source for transformations and schema validation',
```

2024-02-01 23:44 UTC, ecfan commented on apps/vs-code-react/src/app/export/workflowsSelection/advancedOptions.tsx
> +      description: 'Make Integration Account the default source for Transformations and Schema validation',
```suggestion
      description: 'Default to integration account as source for transformations and schema validation',
```

2024-02-01 23:45 UTC, ecfan commented on apps/vs-code-react/src/app/export/workflowsSelection/advancedOptions.tsx
> +      defaultMessage: 'Export Custom Connector Actions as API Management Actions',
```suggestion
      defaultMessage: 'Export custom connector actions as API Management actions',
```

2024-02-01 23:46 UTC, ecfan commented on apps/vs-code-react/src/app/export/workflowsSelection/advancedOptions.tsx
> +      description: 'Export Custom Connector Actions as API Management Actions',
```suggestion
      description: 'Export custom connector actions as API Management actions',
```

2024-02-01 23:47 UTC, ecfan requested changes
Feedback added, thanks!

2024-02-02 18:31 UTC, ecfan approved these changes

2024-02-05 16:44 UTC, hartra344 approved these changes

2024-02-05 17:01 UTC, merged