feat(vscode): IaC Metadata and Fixes
Azure/LogicAppsUX pull request #5724
Opened 2024-09-20 21:44 UTC by lambrianmsft

## Requirement Checklist

* [ ] The commit message follows our guidelines
* [ ] Tests for the changes have been added (for bug fixes or features)
* [ ] Docs have been added or updated (for bug fixes or features)

## Type of Change

* [x] Bug fix
* [ ] Feature
* [ ] Other

## Current Behavior
Added IaC Metadata to each workflow, capturing extension version and bundle version. Fixed regression with func host closing in windows.

## New Behavior
IaC Metadata will be added to each workflow in a logic app. Func hosts launched by the extension in windows will consistently close.

## Impact of Change

* [ ] **This is a breaking change.**

## Screenshots or Videos (if applicable)

2024-09-20 22:33 UTC, hartra344 approved these changes

2024-09-23 16:08 UTC, ccastrotrejo commented on apps/vs-code-designer/package.json
> +  "dependencies": {
Can you move this one to devDependencies?

2024-09-23 16:16 UTC, ccastrotrejo commented on apps/vs-code-designer/src/extensionVariables.ts
Just curious what is the difference between these 3?

2024-09-23 16:17 UTC, ccastrotrejo commented on apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
> +        return files.length === 1 && files[0] === 'workflow.json';
There is a constant for the `workflow.json`

2024-09-23 16:17 UTC, ccastrotrejo requested changes
Writed down comments

2024-09-23 16:34 UTC, lambrianmsft commented on apps/vs-code-designer/src/extensionVariables.ts
currentBundleVersion is the most recent bundle that is found locally and is set to the downloadedBundleVersion since we will download and use the latest bundle.
downloadedBundleVersion is the most recent bundle version available for download.
pinnedBundleVersion tells us if the user has pinned a bundle to a previous version

2024-09-23 18:09 UTC, ccastrotrejo approved these changes

2024-09-23 18:37 UTC, merged