feat(vscode): Logic App and Workflows As Menu Items
Azure/LogicAppsUX pull request #6310
Opened 2024-12-27 01:22 UTC by lambrianmsft

Moved creation of new logic app and new workflows as right click menu items. Removed ability to create logic app outside of a workspace. Refactored to utilize common methods and reduce duplication
## Requirement Checklist

* [ ] The commit message follows our guidelines
* [ ] Tests for the changes have been added (for bug fixes or features)
* [ ] Docs have been added or updated (for bug fixes or features)

## Type of Change

* [ ] Bug fix
* [x] Feature
* [ ] Other

## Current Behavior

Currently customers can create logic app projects without a workspace and currently add new logic app projects and workflows by going to the Azure icon and clicking on the Logic Apps icon as shown.
![image](https://github.com/user-attachments/assets/03a3765a-a797-4c5b-b165-e8fcf1dc8fd2)

## New Behavior

Customers will now be unable to create logic apps outside of a workspace. Customers will now be required to create a logic app workspace that holds their logic app project. Customers will now be able to add new logic app projects and workflows to their workspace by using the right click menu and selecting the appropriate option.
![image](https://github.com/user-attachments/assets/bdf438ac-5cac-486c-a5ce-28a93c817f3c)
![image](https://github.com/user-attachments/assets/548b9c53-9652-43a4-9fe1-c379480134e6)

## Impact of Change

* [x] **This is a breaking change.**

See the new behavior section.

## Screenshots or Videos (if applicable)

2025-01-17 00:29 UTC, ccastrotrejo requested changes

2025-01-17 00:29 UTC, ccastrotrejo commented on apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ConvertToWorkspace.ts
> +        `Full functionality of the Azure Logic Apps (Standard) extension is available only when the workspace is opened. Workspace found at ${wizardContext.workspaceCustomFilePath} that contains the
Tagging @ecfan for improving wording if needed

2025-01-17 00:29 UTC, ccastrotrejo commented on apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ConvertToWorkspace.ts
> +        'Full functionality of the Azure Logic Apps (Standard) extension is available only when logic app project(s) are inside a workspace. Your project(s) will be copied over to the new workspace.
Tagging @ecfan for improving wording if needed

2025-01-17 00:29 UTC, ccastrotrejo commented on apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
> +    if (context.telemetry.properties.isWorkspace !== 'true') {
NIT: While this works, relying on telemetry for control flow decisions could make the code harder to maintain and test and not one of the best practices. Consider having ConvertToWorkspace return a boolean to explicitly indicate success/failure, which would make the behavior more predictable and easier to verify.

2025-01-17 00:29 UTC, ccastrotrejo commented on apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
> +    if (context.telemetry.properties.isWorkspace !== 'true') {
Also you can even do it in a try/catch statement if something goes wrong and we can log telemetry

2025-01-17 00:29 UTC, ccastrotrejo commented on apps/vs-code-designer/src/app/commands/createNewProject/createNewProject.ts
> +  if (context.telemetry.properties.isWorkspace === 'true') {
Same here with the decision making based on the telemetry

2025-01-17 00:29 UTC, ccastrotrejo commented on apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/setMethodName.ts
> +      return localize('functionNameSameAsProjectNameError', 'The function name cannot be the same as the project name.');
Tagging @ecfan for wording improvement if needed

2025-01-17 00:29 UTC, ccastrotrejo commented on apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/InvokeFunctionProjectSetup.ts
> +    const csprojFileContent = templateContent.replace(
What happened here with the method name replacement?

2025-01-17 00:32 UTC, lambrianmsft commented on apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/InvokeFunctionProjectSetup.ts
> +    const csprojFileContent = templateContent.replace(
From what I could tell there isn't that string at all in the file so I removed it.

2025-01-17 22:53 UTC, ccastrotrejo requested changes

2025-01-17 22:53 UTC, ccastrotrejo commented on apps/vs-code-designer/src/app/commands/generateDeploymentScripts/generateDeploymentScripts.ts
> +        ext.outputChannel.appendLog(localize('exitScriptGen', 'Exiting script generation...'));
Are we letting the user know why the generateDeploymentScripts is stopping?

2025-01-17 23:14 UTC, ccastrotrejo approved these changes

2025-01-21 00:40 UTC, ecfan commented on apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ConvertToWorkspace.ts
> +        `Full functionality of the Azure Logic Apps (Standard) extension is available only when the workspace is opened. Workspace found at ${wizardContext.workspaceCustomFilePath} that contains the
```suggestion
        `You must open your workspace to use the full functionality in the Azure Logic Apps (Standard) extension. You can find the workspace with your logic app project at the following location: ${wizardContext.workspaceCustomFilePath}. Do you want to open this workspace now?`
```

2025-01-21 00:43 UTC, ecfan commented on apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ConvertToWorkspace.ts
> +        'Full functionality of the Azure Logic Apps (Standard) extension is available only when logic app project(s) are inside a workspace. Your project(s) will be copied over to the new workspace.
```suggestion
        'Your logic app projects must exist inside a workspace to use the full functionality in the Azure Logic Apps (Standard) extension. Visual Studio Code will copy your projects to a new workspace. Do you want to create the workspace now?'
```

2025-01-21 00:44 UTC, ecfan requested changes
Added feedback.

2025-01-21 00:46 UTC, ecfan commented
@lambrianmsft & @ccastrotrejo: When is the plan to make these changes public? I recently updated our doc about creating Standard workflows with Visual Studio Code. This PR makes substantial changes around behavior and UX options.

Thanks!

2025-01-21 00:49 UTC, ecfan commented on apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/setMethodName.ts
> +      return localize('functionNameSameAsProjectNameError', 'The function name cannot be the same as the project name.');
```suggestion
      return localize('functionNameSameAsProjectNameError', 'Can't use the same name for the function name and the project name.');
```

2025-01-21 00:50 UTC, ecfan commented on apps/vs-code-designer/src/app/commands/createNewCodeProject/createCodeProjectSteps/createFunction/setMethodName.ts
>        return localize('emptyTemplateNameError', 'The function name cannot be empty.');
```suggestion
      return localize('emptyTemplateNameError', 'Can't have an empty function name.');
```

2025-01-21 00:53 UTC, ecfan commented on apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
>      throw new Error(localize('dotnetTemplateError', 'Dotnet templates could not be found.'));
```suggestion
    throw new Error(localize('dotnetTemplateError', 'Can't find dotnet templates.'));
```

2025-01-21 00:53 UTC, ecfan commented on apps/vs-code-designer/src/app/commands/workflows/switchToDotnetProject.ts
> +    `This action moves your Logic App project, ${logicAppFolderName}, to a NuGet-based project. Confirm that you want to move to a NuGet-based project?`
```suggestion
    `This action moves your logic app project, ${logicAppFolderName}, to a NuGet-based project. Confirm that you want to move to a NuGet-based project?`
```

2025-01-21 00:56 UTC, ecfan commented on apps/vs-code-designer/src/app/commands/createNewCodeProject/CodeProjectBase/ConvertToWorkspace.ts
> +          title: localize('convertToWorkspace', 'Convert To Workspace'),
```suggestion
          title: localize('convertToWorkspace', 'Convert to workspace'),
```

2025-01-21 17:59 UTC, ccastrotrejo commented
> @lambrianmsft & @ccastrotrejo: When is the plan to make these changes public? I recently updated our doc about creating Standard workflows with Visual Studio Code. This PR makes substantial changes around behavior and UX options.
> 
> Thanks!

Hi @ecfan we are targeting the release of this update by the first two weeks of Feb

2025-01-21 20:24 UTC, ecfan requested changes
Please let me know when you're done integrating the suggestions. Thanks!

2025-01-21 21:15 UTC, ecfan approved these changes

2025-01-24 21:33 UTC, hartra344 approved these changes

2025-01-24 22:32 UTC, merged